baseURL = 'https://xemiod.github.io/'
languageCode = 'en-us'
title = 'Xemiod ?lab'
theme = 'hugo-flex'

[params]
color = "#42A5F5"
width = "42rem"
divider = "\\a0"
footer = 'Licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>'
rss = "To subscribe to this RSS feed, copy its address and paste it into your favorite feed reader."
noClasses = true
headingoffset = 0
linkicons = false
summaries = true
schema = false
opengraph = true
twittercards = true

[params.utterances]

[params.netlify]
honeypot = false
recaptcha = false

[[menu.nav]]
name = "About"
url = "about/"
weight = 1

[[menu.nav]]
name = "Posts"
url = "post/"
weight = 2

[[menu.nav]]
name = "Tags"
url = "tags/"
weight = 3

[[menu.nav]]
name = "Categories"
url = "categories/"
weight = 4

[[menu.nav]]
name = "RSS"
url = "index.xml"
weight = 5

[mediaTypes."font/woff2"]
suffixes = ["woff2"]
